### PR TITLE
Feature/2729 ng13

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Go Angular 13

Similar to how we feed the showcase in the angular-components repo, I've added the `npm-watch` dependency and some additional tsconfig profiles to the local demo. 

From the example folder:
`yarn start:lib` uses the local version of the auth-workflow.
`yarn start:npm` uses the published auth-workflow.

#### To Test:
- `yarn start:example`

### CODE REVIEW

**Comment by jeffvg** [comment]
do I need to do something with lib? I ran yarn && yarn start:example

image

image

**Comment by jeffvg** [comment]
ignore my comment above. I ran again and it's ok now.

**Comment by jeffvg** [comment]
everything NG13 looks good. I was wondering about the change password screen in the example. It seems to have more height than other screen for some reason.
image

and the create account error state helper text for phone number seems off.
image

**Comment by emclaug2** [comment]
The change password page might look a little off due to the adjusted default padding of the inputs; we can updated the size of the Change Password dialog as part of this PR.

Also the "Code is Required" looks like either a wrong translation, or the wrong text being used.

**Review by jeffvg — APPROVED** [review]
looks  good

**Pull request merged**
